# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
---
version: 1
name: silverblue
description: Custom Fedora Silverblue image for attraktorhh/computers
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest
modules:
  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - cc.arduino.IDE2
          - com.obsproject.Studio
          - com.orcaslicer.OrcaSlicer
          - com.visualstudio.code
          - dev.zed.Zed
          - edu.mit.Scratch
          - net.scribus.Scribus
          - org.freecad.FreeCAD
          - org.gimp.GIMP
          - org.inkscape.Inkscape
          - org.kde.krita
  - type: signing
